INSERT INTO dbo.Sets VALUES ('Red Heart', 47)
GO

INSERT INTO dbo.Pieces VALUES ('Red Heart Heart-shaped Box', 1, 120)
INSERT INTO dbo.Pieces VALUES ('Red Heart Scarlet Candy', 0, 120)
INSERT INTO dbo.Pieces VALUES ('Red Heart Bright Blue Candy', 0, 120)
INSERT INTO dbo.Pieces VALUES ('Red Heart Pastel Yellow Candy', 0, 120)
INSERT INTO dbo.Pieces VALUES ('Red Heart Gold Candy', 0, 120)
INSERT INTO dbo.Pieces VALUES ('Red Heart Pitch Black Candy', 0, 120)
INSERT INTO dbo.Pieces VALUES ('Red Heart Burnt Orange Candy', 0, 120)
INSERT INTO dbo.Pieces VALUES ('Red Heart Rainbow Candy', 0, 120)
INSERT INTO dbo.Pieces VALUES ('Red Heart Hot Pink Candy', 0, 120)
INSERT INTO dbo.Pieces VALUES ('Red Heart Seafoam Green Candy', 0, 120)
GO

INSERT INTO dbo.Collections VALUES ('Redgenies')
INSERT INTO dbo.Collections VALUES ('Bluegenies')
INSERT INTO dbo.Collections VALUES ('Yellowgenies')
GO

INSERT INTO dbo.Sets VALUES ('Vermillion Bottle', 48)
INSERT INTO dbo.Sets VALUES ('Crimson Bottle', 48)
INSERT INTO dbo.Sets VALUES ('Scarlet Bottle', 48)
INSERT INTO dbo.Sets VALUES ('Ruby Bottle', 48)
GO

INSERT INTO dbo.Pieces VALUES ('Vermillion Bottle Spout', 1, 121)
INSERT INTO dbo.Pieces VALUES ('Vermillion Bottle First Vermillion Bottle Shard', 0, 121)
INSERT INTO dbo.Pieces VALUES ('Vermillion Bottle Second Vermillion Bottle Shard', 0, 121)
INSERT INTO dbo.Pieces VALUES ('Vermillion Bottle Third Vermillion Bottle Shard', 0, 121)
INSERT INTO dbo.Pieces VALUES ('Vermillion Bottle Fourth Vermillion Bottle Shard', 0, 121)
INSERT INTO dbo.Pieces VALUES ('Vermillion Bottle Fifth Vermillion Bottle Shard', 0, 121)
INSERT INTO dbo.Pieces VALUES ('Vermillion Bottle Sixth Vermillion Bottle Shard', 0, 121)
INSERT INTO dbo.Pieces VALUES ('Vermillion Bottle Seventh Vermillion Bottle Shard', 0, 121)
INSERT INTO dbo.Pieces VALUES ('Vermillion Bottle Eighth Vermillion Bottle Shard', 0, 121)
INSERT INTO dbo.Pieces VALUES ('Vermillion Bottle Ninth Vermillion Bottle Shard', 0, 121)
INSERT INTO dbo.Pieces VALUES ('Crimson Bottle Spout', 1, 122)
INSERT INTO dbo.Pieces VALUES ('Crimson Bottle First Crimson Bottle Shard', 0, 122)
INSERT INTO dbo.Pieces VALUES ('Crimson Bottle Second Crimson Bottle Shard', 0, 122)
INSERT INTO dbo.Pieces VALUES ('Crimson Bottle Third Crimson Bottle Shard', 0, 122)
INSERT INTO dbo.Pieces VALUES ('Crimson Bottle Fourth Crimson Bottle Shard', 0, 122)
INSERT INTO dbo.Pieces VALUES ('Crimson Bottle Fifth Crimson Bottle Shard', 0, 122)
INSERT INTO dbo.Pieces VALUES ('Crimson Bottle Sixth Crimson Bottle Shard', 0, 122)
INSERT INTO dbo.Pieces VALUES ('Crimson Bottle Seventh Crimson Bottle Shard', 0, 122)
INSERT INTO dbo.Pieces VALUES ('Crimson Bottle Eighth Crimson Bottle Shard', 0, 122)
INSERT INTO dbo.Pieces VALUES ('Crimson Bottle Ninth Crimson Bottle Shard', 0, 122)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bottle Spout', 1, 123)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bottle First Scarlet Bottle Shard', 0, 123)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bottle Second Scarlet Bottle Shard', 0, 123)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bottle Third Scarlet Bottle Shard', 0, 123)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bottle Fourth Scarlet Bottle Shard', 0, 123)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bottle Fifth Scarlet Bottle Shard', 0, 123)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bottle Sixth Scarlet Bottle Shard', 0, 123)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bottle Seventh Scarlet Bottle Shard', 0, 123)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bottle Eighth Scarlet Bottle Shard', 0, 123)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bottle Ninth Scarlet Bottle Shard', 0, 123)
INSERT INTO dbo.Pieces VALUES ('Ruby Bottle Spout', 1, 124)
INSERT INTO dbo.Pieces VALUES ('Ruby Bottle First Ruby Bottle Shard', 0, 124)
INSERT INTO dbo.Pieces VALUES ('Ruby Bottle Second Ruby Bottle Shard', 0, 124)
INSERT INTO dbo.Pieces VALUES ('Ruby Bottle Third Ruby Bottle Shard', 0, 124)
INSERT INTO dbo.Pieces VALUES ('Ruby Bottle Fourth Ruby Bottle Shard', 0, 124)
INSERT INTO dbo.Pieces VALUES ('Ruby Bottle Fifth Ruby Bottle Shard', 0, 124)
INSERT INTO dbo.Pieces VALUES ('Ruby Bottle Sixth Ruby Bottle Shard', 0, 124)
INSERT INTO dbo.Pieces VALUES ('Ruby Bottle Seventh Ruby Bottle Shard', 0, 124)
INSERT INTO dbo.Pieces VALUES ('Ruby Bottle Eighth Ruby Bottle Shard', 0, 124)
INSERT INTO dbo.Pieces VALUES ('Ruby Bottle Ninth Ruby Bottle Shard', 0, 124)
GO

INSERT INTO dbo.Sets VALUES ('Cerulean Bottle', 49)
INSERT INTO dbo.Sets VALUES ('Sapphire Bottle', 49)
INSERT INTO dbo.Sets VALUES ('Lavender Bottle', 49)
INSERT INTO dbo.Sets VALUES ('Azure Bottle', 49)
INSERT INTO dbo.Sets VALUES ('Gold Bottle', 50)
INSERT INTO dbo.Sets VALUES ('Saffron Bottle', 50)
INSERT INTO dbo.Sets VALUES ('Citrine Bottle', 50)
INSERT INTO dbo.Sets VALUES ('Amber Bottle', 50)
GO

INSERT INTO dbo.Pieces VALUES ('Cerulean Bottle Spout', 1, 125)
INSERT INTO dbo.Pieces VALUES ('Cerulean Bottle First Cerulean Bottle Shard', 0, 125)
INSERT INTO dbo.Pieces VALUES ('Cerulean Bottle Second Cerulean Bottle Shard', 0, 125)
INSERT INTO dbo.Pieces VALUES ('Cerulean Bottle Third Cerulean Bottle Shard', 0, 125)
INSERT INTO dbo.Pieces VALUES ('Cerulean Bottle Fourth Cerulean Bottle Shard', 0, 125)
INSERT INTO dbo.Pieces VALUES ('Cerulean Bottle Fifth Cerulean Bottle Shard', 0, 125)
INSERT INTO dbo.Pieces VALUES ('Cerulean Bottle Sixth Cerulean Bottle Shard', 0, 125)
INSERT INTO dbo.Pieces VALUES ('Cerulean Bottle Seventh Cerulean Bottle Shard', 0, 125)
INSERT INTO dbo.Pieces VALUES ('Cerulean Bottle Eighth Cerulean Bottle Shard', 0, 125)
INSERT INTO dbo.Pieces VALUES ('Cerulean Bottle Ninth Cerulean Bottle Shard', 0, 125)
INSERT INTO dbo.Pieces VALUES ('Sapphire Bottle Spout', 1, 126)
INSERT INTO dbo.Pieces VALUES ('Sapphire Bottle First Sapphire Bottle Shard', 0, 126)
INSERT INTO dbo.Pieces VALUES ('Sapphire Bottle Second Sapphire Bottle Shard', 0, 126)
INSERT INTO dbo.Pieces VALUES ('Sapphire Bottle Third Sapphire Bottle Shard', 0, 126)
INSERT INTO dbo.Pieces VALUES ('Sapphire Bottle Fourth Sapphire Bottle Shard', 0, 126)
INSERT INTO dbo.Pieces VALUES ('Sapphire Bottle Fifth Sapphire Bottle Shard', 0, 126)
INSERT INTO dbo.Pieces VALUES ('Sapphire Bottle Sixth Sapphire Bottle Shard', 0, 126)
INSERT INTO dbo.Pieces VALUES ('Sapphire Bottle Seventh Sapphire Bottle Shard', 0, 126)
INSERT INTO dbo.Pieces VALUES ('Sapphire Bottle Eighth Sapphire Bottle Shard', 0, 126)
INSERT INTO dbo.Pieces VALUES ('Sapphire Bottle Ninth Sapphire Bottle Shard', 0, 126)
INSERT INTO dbo.Pieces VALUES ('Lavender Bottle Spout', 1, 127)
INSERT INTO dbo.Pieces VALUES ('Lavender Bottle First Lavender Bottle Shard', 0, 127)
INSERT INTO dbo.Pieces VALUES ('Lavender Bottle Second Lavender Bottle Shard', 0, 127)
INSERT INTO dbo.Pieces VALUES ('Lavender Bottle Third Lavender Bottle Shard', 0, 127)
INSERT INTO dbo.Pieces VALUES ('Lavender Bottle Fourth Lavender Bottle Shard', 0, 127)
INSERT INTO dbo.Pieces VALUES ('Lavender Bottle Fifth Lavender Bottle Shard', 0, 127)
INSERT INTO dbo.Pieces VALUES ('Lavender Bottle Sixth Lavender Bottle Shard', 0, 127)
INSERT INTO dbo.Pieces VALUES ('Lavender Bottle Seventh Lavender Bottle Shard', 0, 127)
INSERT INTO dbo.Pieces VALUES ('Lavender Bottle Eighth Lavender Bottle Shard', 0, 127)
INSERT INTO dbo.Pieces VALUES ('Lavender Bottle Ninth Lavender Bottle Shard', 0, 127)
INSERT INTO dbo.Pieces VALUES ('Azure Bottle Spout', 1, 128)
INSERT INTO dbo.Pieces VALUES ('Azure Bottle First Azure Bottle Shard', 0, 128)
INSERT INTO dbo.Pieces VALUES ('Azure Bottle Second Azure Bottle Shard', 0, 128)
INSERT INTO dbo.Pieces VALUES ('Azure Bottle Third Azure Bottle Shard', 0, 128)
INSERT INTO dbo.Pieces VALUES ('Azure Bottle Fourth Azure Bottle Shard', 0, 128)
INSERT INTO dbo.Pieces VALUES ('Azure Bottle Fifth Azure Bottle Shard', 0, 128)
INSERT INTO dbo.Pieces VALUES ('Azure Bottle Sixth Azure Bottle Shard', 0, 128)
INSERT INTO dbo.Pieces VALUES ('Azure Bottle Seventh Azure Bottle Shard', 0, 128)
INSERT INTO dbo.Pieces VALUES ('Azure Bottle Eighth Azure Bottle Shard', 0, 128)
INSERT INTO dbo.Pieces VALUES ('Azure Bottle Ninth Azure Bottle Shard', 0, 128)
INSERT INTO dbo.Pieces VALUES ('Gold Bottle Spout', 1, 129)
INSERT INTO dbo.Pieces VALUES ('Gold Bottle First Gold Bottle Shard', 0, 129)
INSERT INTO dbo.Pieces VALUES ('Gold Bottle Second Gold Bottle Shard', 0, 129)
INSERT INTO dbo.Pieces VALUES ('Gold Bottle Third Gold Bottle Shard', 0, 129)
INSERT INTO dbo.Pieces VALUES ('Gold Bottle Fourth Gold Bottle Shard', 0, 129)
INSERT INTO dbo.Pieces VALUES ('Gold Bottle Fifth Gold Bottle Shard', 0, 129)
INSERT INTO dbo.Pieces VALUES ('Gold Bottle Sixth Gold Bottle Shard', 0, 129)
INSERT INTO dbo.Pieces VALUES ('Gold Bottle Seventh Gold Bottle Shard', 0, 129)
INSERT INTO dbo.Pieces VALUES ('Gold Bottle Eighth Gold Bottle Shard', 0, 129)
INSERT INTO dbo.Pieces VALUES ('Gold Bottle Ninth Gold Bottle Shard', 0, 129)
INSERT INTO dbo.Pieces VALUES ('Saffron Bottle Spout', 1, 130)
INSERT INTO dbo.Pieces VALUES ('Saffron Bottle First Saffron Bottle Shard', 0, 130)
INSERT INTO dbo.Pieces VALUES ('Saffron Bottle Second Saffron Bottle Shard', 0, 130)
INSERT INTO dbo.Pieces VALUES ('Saffron Bottle Third Saffron Bottle Shard', 0, 130)
INSERT INTO dbo.Pieces VALUES ('Saffron Bottle Fourth Saffron Bottle Shard', 0, 130)
INSERT INTO dbo.Pieces VALUES ('Saffron Bottle Fifth Saffron Bottle Shard', 0, 130)
INSERT INTO dbo.Pieces VALUES ('Saffron Bottle Sixth Saffron Bottle Shard', 0, 130)
INSERT INTO dbo.Pieces VALUES ('Saffron Bottle Seventh Saffron Bottle Shard', 0, 130)
INSERT INTO dbo.Pieces VALUES ('Saffron Bottle Eighth Saffron Bottle Shard', 0, 130)
INSERT INTO dbo.Pieces VALUES ('Saffron Bottle Ninth Saffron Bottle Shard', 0, 130)
INSERT INTO dbo.Pieces VALUES ('Citrine Bottle Spout', 1, 131)
INSERT INTO dbo.Pieces VALUES ('Citrine Bottle First Citrine Bottle Shard', 0, 131)
INSERT INTO dbo.Pieces VALUES ('Citrine Bottle Second Citrine Bottle Shard', 0, 131)
INSERT INTO dbo.Pieces VALUES ('Citrine Bottle Third Citrine Bottle Shard', 0, 131)
INSERT INTO dbo.Pieces VALUES ('Citrine Bottle Fourth Citrine Bottle Shard', 0, 131)
INSERT INTO dbo.Pieces VALUES ('Citrine Bottle Fifth Citrine Bottle Shard', 0, 131)
INSERT INTO dbo.Pieces VALUES ('Citrine Bottle Sixth Citrine Bottle Shard', 0, 131)
INSERT INTO dbo.Pieces VALUES ('Citrine Bottle Seventh Citrine Bottle Shard', 0, 131)
INSERT INTO dbo.Pieces VALUES ('Citrine Bottle Eighth Citrine Bottle Shard', 0, 131)
INSERT INTO dbo.Pieces VALUES ('Citrine Bottle Ninth Citrine Bottle Shard', 0, 131)
INSERT INTO dbo.Pieces VALUES ('Amber Bottle Spout', 1, 132)
INSERT INTO dbo.Pieces VALUES ('Amber Bottle First Amber Bottle Shard', 0, 132)
INSERT INTO dbo.Pieces VALUES ('Amber Bottle Second Amber Bottle Shard', 0, 132)
INSERT INTO dbo.Pieces VALUES ('Amber Bottle Third Amber Bottle Shard', 0, 132)
INSERT INTO dbo.Pieces VALUES ('Amber Bottle Fourth Amber Bottle Shard', 0, 132)
INSERT INTO dbo.Pieces VALUES ('Amber Bottle Fifth Amber Bottle Shard', 0, 132)
INSERT INTO dbo.Pieces VALUES ('Amber Bottle Sixth Amber Bottle Shard', 0, 132)
INSERT INTO dbo.Pieces VALUES ('Amber Bottle Seventh Amber Bottle Shard', 0, 132)
INSERT INTO dbo.Pieces VALUES ('Amber Bottle Eighth Amber Bottle Shard', 0, 132)
INSERT INTO dbo.Pieces VALUES ('Amber Bottle Ninth Amber Bottle Shard', 0, 132)
GO

INSERT INTO dbo.Collections VALUES ('Fried')
INSERT INTO dbo.Collections VALUES ('Chocolate')
GO

INSERT INTO dbo.Sets VALUES ('Allspice Bottle', 51)
INSERT INTO dbo.Sets VALUES ('Powdered Sugar Bottle', 52)
INSERT INTO dbo.Sets VALUES ('Love Bottle', 52)
INSERT INTO dbo.Sets VALUES ('White Bubble', 47)
INSERT INTO dbo.Sets VALUES ('Purple Bubble', 47)
INSERT INTO dbo.Sets VALUES ('Grey Bubble', 47)
INSERT INTO dbo.Sets VALUES ('Black bubble', 47)
GO

INSERT INTO dbo.Pieces VALUES ('Allspice Bottle Empty Allspice Bottle', 1, 133)
INSERT INTO dbo.Pieces VALUES ('Allspice Bottle First Pinch Of Allspice', 0, 133)
INSERT INTO dbo.Pieces VALUES ('Allspice Bottle Second Pinch Of Allspice', 0, 133)
INSERT INTO dbo.Pieces VALUES ('Allspice Bottle Third Pinch Of Allspice', 0, 133)
INSERT INTO dbo.Pieces VALUES ('Allspice Bottle Fourth Pinch Of Allspice', 0, 133)
INSERT INTO dbo.Pieces VALUES ('Allspice Bottle Fifth Pinch Of Allspice', 0, 133)
INSERT INTO dbo.Pieces VALUES ('Allspice Bottle Sixth Pinch Of Allspice', 0, 133)
INSERT INTO dbo.Pieces VALUES ('Allspice Bottle Seventh Pinch Of Allspice', 0, 133)
INSERT INTO dbo.Pieces VALUES ('Allspice Bottle Eighth Pinch Of Allspice', 0, 133)
INSERT INTO dbo.Pieces VALUES ('Allspice Bottle Ninth Pinch Of Allspice', 0, 133)
INSERT INTO dbo.Pieces VALUES ('Powdered Sugar Bottle Spout', 1, 134)
INSERT INTO dbo.Pieces VALUES ('Powdered Sugar Bottle First Pinch Of Powdered Sugar', 0, 134)
INSERT INTO dbo.Pieces VALUES ('Powdered Sugar Bottle Second Pinch Of Powdered Sugar', 0, 134)
INSERT INTO dbo.Pieces VALUES ('Powdered Sugar Bottle Third Pinch Of Powdered Sugar', 0, 134)
INSERT INTO dbo.Pieces VALUES ('Powdered Sugar Bottle Fourth Pinch Of Powdered Sugar', 0, 134)
INSERT INTO dbo.Pieces VALUES ('Powdered Sugar Bottle Fifth Pinch Of Powdered Sugar', 0, 134)
INSERT INTO dbo.Pieces VALUES ('Powdered Sugar Bottle Sixth Pinch Of Powdered Sugar', 0, 134)
INSERT INTO dbo.Pieces VALUES ('Powdered Sugar Bottle Seventh Pinch Of Powdered Sugar', 0, 134)
INSERT INTO dbo.Pieces VALUES ('Powdered Sugar Bottle Eighth Pinch Of Powdered Sugar', 0, 134)
INSERT INTO dbo.Pieces VALUES ('Powdered Sugar Bottle Ninth Pinch Of Powdered Sugar', 0, 134)
INSERT INTO dbo.Pieces VALUES ('Love Bottle Spout', 1, 135)
INSERT INTO dbo.Pieces VALUES ('Love Bottle First Dollop Of Love', 0, 135)
INSERT INTO dbo.Pieces VALUES ('Love Bottle Second Dollop Of Love', 0, 135)
INSERT INTO dbo.Pieces VALUES ('Love Bottle Third Dollop Of Love', 0, 135)
INSERT INTO dbo.Pieces VALUES ('Love Bottle Fourth Dollop Of Love', 0, 135)
INSERT INTO dbo.Pieces VALUES ('Love Bottle Fifth Dollop Of Love', 0, 135)
INSERT INTO dbo.Pieces VALUES ('Love Bottle Sixth Dollop Of Love', 0, 135)
INSERT INTO dbo.Pieces VALUES ('Love Bottle Seventh Dollop Of Love', 0, 135)
INSERT INTO dbo.Pieces VALUES ('Love Bottle Eighth Dollop Of Love', 0, 135)
INSERT INTO dbo.Pieces VALUES ('Love Bottle Ninth Dollop Of Love', 0, 135)
INSERT INTO dbo.Pieces VALUES ('White Bubble White Bubble Shell', 1, 136)
INSERT INTO dbo.Pieces VALUES ('White Bubble Essence Of Chaos', 0, 136)
INSERT INTO dbo.Pieces VALUES ('White Bubble Essence Of Death', 0, 136)
INSERT INTO dbo.Pieces VALUES ('White Bubble Essence Of Knowledge', 0, 136)
INSERT INTO dbo.Pieces VALUES ('White Bubble Essence Of Beauty', 0, 136)
INSERT INTO dbo.Pieces VALUES ('White Bubble Essence Of Life', 0, 136)
INSERT INTO dbo.Pieces VALUES ('White Bubble Essence Of Justice', 0, 136)
INSERT INTO dbo.Pieces VALUES ('White Bubble Essence Of Nature', 0, 136)
INSERT INTO dbo.Pieces VALUES ('White Bubble Essence Of Harmony', 0, 136)
INSERT INTO dbo.Pieces VALUES ('White Bubble Essence Of War', 0, 136)
INSERT INTO dbo.Pieces VALUES ('Purple Bubble Purple Bubble Shell', 1, 137)
INSERT INTO dbo.Pieces VALUES ('Purple Bubble Butterfly Wings', 0, 137)
INSERT INTO dbo.Pieces VALUES ('Purple Bubble Perfume Bottle', 0, 137)
INSERT INTO dbo.Pieces VALUES ('Purple Bubble Mrriak Fur', 0, 137)
INSERT INTO dbo.Pieces VALUES ('Purple Bubble Aerial Feather', 0, 137)
INSERT INTO dbo.Pieces VALUES ('Purple Bubble Essence Of Snootiness', 0, 137)
INSERT INTO dbo.Pieces VALUES ('Purple Bubble Gardener''s Hat', 0, 137)
INSERT INTO dbo.Pieces VALUES ('Purple Bubble Flower Petals', 0, 137)
INSERT INTO dbo.Pieces VALUES ('Purple Bubble Maid''s Feather Duster', 0, 137)
INSERT INTO dbo.Pieces VALUES ('Purple Bubble Trill Feather', 0, 137)
INSERT INTO dbo.Pieces VALUES ('Grey Bubble Grey Bubble Shell', 1, 138)
INSERT INTO dbo.Pieces VALUES ('Grey Bubble Wolf Hair', 0, 138)
INSERT INTO dbo.Pieces VALUES ('Grey Bubble Hunter''s Knife', 0, 138)
INSERT INTO dbo.Pieces VALUES ('Grey Bubble Lupine Ectoplasm', 0, 138)
INSERT INTO dbo.Pieces VALUES ('Grey Bubble Green Grass', 0, 138)
INSERT INTO dbo.Pieces VALUES ('Grey Bubble Tidepool Water', 0, 138)
INSERT INTO dbo.Pieces VALUES ('Grey Bubble Standing Stone Chip', 0, 138)
INSERT INTO dbo.Pieces VALUES ('Grey Bubble Splinter Of A Wood Hut', 0, 138)
INSERT INTO dbo.Pieces VALUES ('Grey Bubble Fire Pit Ember', 0, 138)
INSERT INTO dbo.Pieces VALUES ('Grey Bubble Creek Stone', 0, 138)
INSERT INTO dbo.Pieces VALUES ('Black Bubble Black Bubble Shell', 1, 139)
INSERT INTO dbo.Pieces VALUES ('Black Bubble Fox Tail', 0, 139)
INSERT INTO dbo.Pieces VALUES ('Black Bubble Badger Tooth', 0, 139)
INSERT INTO dbo.Pieces VALUES ('Black Bubble Buck Horn', 0, 139)
INSERT INTO dbo.Pieces VALUES ('Black Bubble Cup Of Slime', 0, 139)
INSERT INTO dbo.Pieces VALUES ('Black Bubble Zombie Hand', 0, 139)
INSERT INTO dbo.Pieces VALUES ('Black Bubble Tendril Skin', 0, 139)
INSERT INTO dbo.Pieces VALUES ('Black Bubble Jar Of Tar', 0, 139)
INSERT INTO dbo.Pieces VALUES ('Black Bubble Petrified Tree Bark', 0, 139)
INSERT INTO dbo.Pieces VALUES ('Black Bubble Puddle Of Muck', 0, 139)
GO

INSERT INTO dbo.Sets VALUES ('Poteen Pot', 47)
GO

INSERT INTO dbo.Pieces VALUES ('Poteen Pot Poteen Pot', 1, 140)
INSERT INTO dbo.Pieces VALUES ('Poteen Pot Barrel Of Barley', 0, 140)
INSERT INTO dbo.Pieces VALUES ('Poteen Pot Handful Of Oats', 0, 140)
INSERT INTO dbo.Pieces VALUES ('Poteen Pot Fistful Of Rye', 0, 140)
INSERT INTO dbo.Pieces VALUES ('Poteen Pot Yummy Taters', 0, 140)
INSERT INTO dbo.Pieces VALUES ('Poteen Pot Malty Malt', 0, 140)
INSERT INTO dbo.Pieces VALUES ('Poteen Pot Treacle', 0, 140)
INSERT INTO dbo.Pieces VALUES ('Poteen Pot Sour Mash', 0, 140)
INSERT INTO dbo.Pieces VALUES ('Poteen Pot Washed Sand', 0, 140)
INSERT INTO dbo.Pieces VALUES ('Poteen Pot Bit O Magic', 0, 140)
GO

INSERT INTO dbo.Pieces VALUES ('straight razor straight razor rust', 0, 73)
GO

INSERT INTO dbo.Sets VALUES ('Mouldy Cheese', 47)
GO

INSERT INTO dbo.Pieces VALUES ('Mouldy Cheese Cheese Rind', 1, 141)
INSERT INTO dbo.Pieces VALUES ('Mouldy Cheese Green Mould', 0, 141)
INSERT INTO dbo.Pieces VALUES ('Mouldy Cheese Blue Mould', 0, 141)
INSERT INTO dbo.Pieces VALUES ('Mouldy Cheese Purple Mould', 0, 141)
INSERT INTO dbo.Pieces VALUES ('Mouldy Cheese Red Mould', 0, 141)
INSERT INTO dbo.Pieces VALUES ('Mouldy Cheese Yellow Mould', 0, 141)
INSERT INTO dbo.Pieces VALUES ('Mouldy Cheese Grey Mould', 0, 141)
INSERT INTO dbo.Pieces VALUES ('Mouldy Cheese Black Mould', 0, 141)
INSERT INTO dbo.Pieces VALUES ('Mouldy Cheese White Mould', 0, 141)
INSERT INTO dbo.Pieces VALUES ('Mouldy Cheese Orange Mould', 0, 141)
GO

INSERT INTO dbo.Sets VALUES ('Jester Mask', 47)
GO

INSERT INTO dbo.Pieces VALUES ('Jester Mask Jester Right Eye', 0, 142)
GO

INSERT INTO dbo.Collections VALUES ('Pasta')
INSERT INTO dbo.Collections VALUES ('Cupcake')
INSERT INTO dbo.Collections VALUES ('Spice')
GO

INSERT INTO dbo.Sets VALUES ('Leprechaun Pot', 47)
INSERT INTO dbo.Sets VALUES ('Parsley Bottle', 53)
INSERT INTO dbo.Sets VALUES ('Kelpie Mask', 47)
INSERT INTO dbo.Sets VALUES ('Swan Mask', 47)
INSERT INTO dbo.Sets VALUES ('Chicken Mask', 47)
INSERT INTO dbo.Sets VALUES ('Maiden Mask', 47)
INSERT INTO dbo.Sets VALUES ('Yellow Bottle', 54)
INSERT INTO dbo.Sets VALUES ('Butterfly Mask', 47)
INSERT INTO dbo.Sets VALUES ('Rosemary Bottle', 53)
INSERT INTO dbo.Sets VALUES ('Clove Bottle', 55)
INSERT INTO dbo.Sets VALUES ('Sand Bubble', 47)
GO

INSERT INTO dbo.Pieces VALUES ('Leprechaun Pot Laughter', 0, 143)
INSERT INTO dbo.Pieces VALUES ('Parsley Bottle First Pinch Of Parsley', 0, 144)
INSERT INTO dbo.Pieces VALUES ('Parsley Bottle Second Pinch Of Parsley', 0, 144)
INSERT INTO dbo.Pieces VALUES ('Parsley Bottle Third Pinch Of Parsley', 0, 144)
INSERT INTO dbo.Pieces VALUES ('Parsley Bottle Fourth Pinch Of Parsley', 0, 144)
INSERT INTO dbo.Pieces VALUES ('Parsley Bottle Fifth Pinch Of Parsley', 0, 144)
INSERT INTO dbo.Pieces VALUES ('Parsley Bottle Sixth Pinch Of Parsley', 0, 144)
INSERT INTO dbo.Pieces VALUES ('Parsley Bottle Seventh Pinch Of Parsley', 0, 144)
INSERT INTO dbo.Pieces VALUES ('Parsley Bottle Eighth Pinch Of Parsley', 0, 144)
INSERT INTO dbo.Pieces VALUES ('Parsley Bottle Ninth Pinch Of Parsley', 0, 144)
INSERT INTO dbo.Pieces VALUES ('Kelpie Mask Kelpie Upper Mouth', 0, 145)
INSERT INTO dbo.Pieces VALUES ('Swan Mask Swan Chin', 0, 146)
INSERT INTO dbo.Pieces VALUES ('Chicken Mask Chicken Left Cheek', 0, 147)
INSERT INTO dbo.Pieces VALUES ('Maiden Mask Maiden Mask Strap', 0, 148)
INSERT INTO dbo.Pieces VALUES ('Yellow Bottle Empty Yellow Sprinkles Bottle', 1, 149)
INSERT INTO dbo.Pieces VALUES ('Butterfly Mask Butterfly Mask Head', 1, 150)
INSERT INTO dbo.Pieces VALUES ('Rosemary Bottle First Pinch Of Rosemary', 0, 151)
INSERT INTO dbo.Pieces VALUES ('Rosemary Bottle Second Pinch Of Rosemary', 0, 151)
INSERT INTO dbo.Pieces VALUES ('Rosemary Bottle Third Pinch Of Rosemary', 0, 151)
INSERT INTO dbo.Pieces VALUES ('Rosemary Bottle Fourth Pinch Of Rosemary', 0, 151)
INSERT INTO dbo.Pieces VALUES ('Rosemary Bottle Fifth Pinch Of Rosemary', 0, 151)
INSERT INTO dbo.Pieces VALUES ('Rosemary Bottle Sixth Pinch Of Rosemary', 0, 151)
INSERT INTO dbo.Pieces VALUES ('Rosemary Bottle Seventh Pinch Of Rosemary', 0, 151)
INSERT INTO dbo.Pieces VALUES ('Rosemary Bottle Eighth Pinch Of Rosemary', 0, 151)
INSERT INTO dbo.Pieces VALUES ('Rosemary Bottle Ninth Pinch Of Rosemary', 0, 151)
INSERT INTO dbo.Pieces VALUES ('Clove Bottle First Pinch Of Cloves', 0, 152)
INSERT INTO dbo.Pieces VALUES ('Clove Bottle Second Pinch Of Cloves', 0, 152)
INSERT INTO dbo.Pieces VALUES ('Clove Bottle Third Pinch Of Cloves', 0, 152)
INSERT INTO dbo.Pieces VALUES ('Clove Bottle Fourth Pinch Of Cloves', 0, 152)
INSERT INTO dbo.Pieces VALUES ('Clove Bottle Fifth Pinch Of Cloves', 0, 152)
INSERT INTO dbo.Pieces VALUES ('Clove Bottle Sixth Pinch Of Cloves', 0, 152)
INSERT INTO dbo.Pieces VALUES ('Clove Bottle Seventh Pinch Of Cloves', 0, 152)
INSERT INTO dbo.Pieces VALUES ('Clove Bottle Eighth Pinch Of Cloves', 0, 152)
INSERT INTO dbo.Pieces VALUES ('Clove Bottle Ninth Pinch Of Cloves', 0, 152)
INSERT INTO dbo.Pieces VALUES ('Sand Bubble Sandworm Tooth', 0, 153)
GO

INSERT INTO dbo.Sets VALUES ('Conflict Bubble', 47)
INSERT INTO dbo.Sets VALUES ('Scarlet Bubble', 47)
INSERT INTO dbo.Sets VALUES ('Green Bubble', 47)
INSERT INTO dbo.Sets VALUES ('Silk Bubble', 47)
INSERT INTO dbo.Sets VALUES ('Gas Bubble', 47)
INSERT INTO dbo.Sets VALUES ('Ice Bubble', 47)
INSERT INTO dbo.Sets VALUES ('Lava Bubble', 47)
INSERT INTO dbo.Sets VALUES ('Sable Bubble', 47)
INSERT INTO dbo.Sets VALUES ('Smoke Bubble', 47)
GO

INSERT INTO dbo.Pieces VALUES ('Leprechaun Pot Pot', 1, 143)
INSERT INTO dbo.Pieces VALUES ('Leprechaun Pot Jade Shamrock', 0, 143)
INSERT INTO dbo.Pieces VALUES ('Leprechaun Pot Onyx Shamrock', 0, 143)
INSERT INTO dbo.Pieces VALUES ('Leprechaun Pot Peppermint Shamrock', 0, 143)
INSERT INTO dbo.Pieces VALUES ('Leprechaun Pot Rainbows', 0, 143)
INSERT INTO dbo.Pieces VALUES ('Leprechaun Pot Hugs', 0, 143)
INSERT INTO dbo.Pieces VALUES ('Leprechaun Pot Silliness', 0, 143)
INSERT INTO dbo.Pieces VALUES ('Leprechaun Pot Lucky Charms', 0, 143)
INSERT INTO dbo.Pieces VALUES ('Leprechaun Pot Smiles', 0, 143)
INSERT INTO dbo.Pieces VALUES ('Conflict Bubble Conflict Bubble Shell', 1, 154)
INSERT INTO dbo.Pieces VALUES ('Conflict Bubble Stoat Fur', 0, 154)
INSERT INTO dbo.Pieces VALUES ('Conflict Bubble Kestrel Feather', 0, 154)
INSERT INTO dbo.Pieces VALUES ('Conflict Bubble Cougar Tooth', 0, 154)
INSERT INTO dbo.Pieces VALUES ('Conflict Bubble Dingo Tooth', 0, 154)
INSERT INTO dbo.Pieces VALUES ('Conflict Bubble Manticore Stinger', 0, 154)
INSERT INTO dbo.Pieces VALUES ('Conflict Bubble Fox Tail', 0, 154)
INSERT INTO dbo.Pieces VALUES ('Conflict Bubble Bear Talon', 0, 154)
INSERT INTO dbo.Pieces VALUES ('Conflict Bubble Aslaran Knife', 0, 154)
INSERT INTO dbo.Pieces VALUES ('Conflict Bubble Krokani Spear', 0, 154)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bubble Scarlet Bubble Shell', 1, 156)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bubble Drop Of Black Oil', 0, 156)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bubble Brains', 0, 156)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bubble Nighthawk Feather', 0, 156)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bubble Lich Tongue', 0, 156)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bubble Aphid Juice', 0, 156)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bubble Touch Of Horror', 0, 156)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bubble Essence Of The Undead', 0, 156)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bubble Demon Toenail', 0, 156)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bubble Bloody Blossoms', 0, 156)
INSERT INTO dbo.Pieces VALUES ('Green Bubble Green Bubble Shell', 1, 157)
INSERT INTO dbo.Pieces VALUES ('Green Bubble Roc Feather', 0, 157)
INSERT INTO dbo.Pieces VALUES ('Green Bubble Raccoon Tail', 0, 157)
INSERT INTO dbo.Pieces VALUES ('Green Bubble Owl Beak', 0, 157)
INSERT INTO dbo.Pieces VALUES ('Green Bubble Roan Tail', 0, 157)
INSERT INTO dbo.Pieces VALUES ('Green Bubble Platypus Bill', 0, 157)
INSERT INTO dbo.Pieces VALUES ('Green Bubble Lamb Wool', 0, 157)
INSERT INTO dbo.Pieces VALUES ('Green Bubble Dog Spittle', 0, 157)
INSERT INTO dbo.Pieces VALUES ('Green Bubble Valley Flowers', 0, 157)
INSERT INTO dbo.Pieces VALUES ('Green Bubble Green Grass', 0, 157)
INSERT INTO dbo.Pieces VALUES ('Silk Bubble Silk Bubble Shell', 1, 158)
INSERT INTO dbo.Pieces VALUES ('Silk Bubble Frog''s Leg', 0, 158)
INSERT INTO dbo.Pieces VALUES ('Silk Bubble Silkworm Shell', 0, 158)
INSERT INTO dbo.Pieces VALUES ('Silk Bubble Caterpillar Legs', 0, 158)
INSERT INTO dbo.Pieces VALUES ('Silk Bubble Eye Of Newt', 0, 158)
INSERT INTO dbo.Pieces VALUES ('Silk Bubble Moth Wings', 0, 158)
INSERT INTO dbo.Pieces VALUES ('Silk Bubble Rabbit''s Foot', 0, 158)
INSERT INTO dbo.Pieces VALUES ('Silk Bubble Tae''dae''s Glove', 0, 158)
INSERT INTO dbo.Pieces VALUES ('Silk Bubble Furrikin''s Hat', 0, 158)
INSERT INTO dbo.Pieces VALUES ('Silk Bubble Drop Of Bee Honey', 0, 158)
INSERT INTO dbo.Pieces VALUES ('Gas Bubble Gas Bubble Shell', 1, 159)
INSERT INTO dbo.Pieces VALUES ('Gas Bubble Alligator Skin', 0, 159)
INSERT INTO dbo.Pieces VALUES ('Gas Bubble Turtle Shell', 0, 159)
INSERT INTO dbo.Pieces VALUES ('Gas Bubble Eye Of Frog', 0, 159)
INSERT INTO dbo.Pieces VALUES ('Gas Bubble Python Skin', 0, 159)
INSERT INTO dbo.Pieces VALUES ('Gas Bubble Swamp Water', 0, 159)
INSERT INTO dbo.Pieces VALUES ('Gas Bubble Mosquitos', 0, 159)
INSERT INTO dbo.Pieces VALUES ('Gas Bubble Rotting Plants', 0, 159)
INSERT INTO dbo.Pieces VALUES ('Gas Bubble Essence Of Decay', 0, 159)
INSERT INTO dbo.Pieces VALUES ('Gas Bubble Mugwump Spittle', 0, 159)
INSERT INTO dbo.Pieces VALUES ('Ice Bubble Ice Bubble Shell', 1, 160)
INSERT INTO dbo.Pieces VALUES ('Ice Bubble Snow Essence', 0, 160)
INSERT INTO dbo.Pieces VALUES ('Ice Bubble Mammoth Tusk', 0, 160)
INSERT INTO dbo.Pieces VALUES ('Ice Bubble Eagle Feather', 0, 160)
INSERT INTO dbo.Pieces VALUES ('Ice Bubble Igasho Hair', 0, 160)
INSERT INTO dbo.Pieces VALUES ('Ice Bubble Sabretooth Fang', 0, 160)
INSERT INTO dbo.Pieces VALUES ('Ice Bubble Hare Ear', 0, 160)
INSERT INTO dbo.Pieces VALUES ('Ice Bubble Cave Dirt', 0, 160)
INSERT INTO dbo.Pieces VALUES ('Ice Bubble Taurian Horn', 0, 160)
INSERT INTO dbo.Pieces VALUES ('Ice Bubble Chunk Of Ice', 0, 160)
INSERT INTO dbo.Pieces VALUES ('Lava Bubble Lava Bubble Shell', 1, 161)
INSERT INTO dbo.Pieces VALUES ('Lava Bubble Cup Of Lava', 0, 161)
INSERT INTO dbo.Pieces VALUES ('Lava Bubble Volcanic Rock', 0, 161)
INSERT INTO dbo.Pieces VALUES ('Lava Bubble Wyvern Feather', 0, 161)
INSERT INTO dbo.Pieces VALUES ('Lava Bubble Coeurl Whiskers', 0, 161)
INSERT INTO dbo.Pieces VALUES ('Lava Bubble Kanzakage Claw', 0, 161)
INSERT INTO dbo.Pieces VALUES ('Lava Bubble Desert Crab Shell', 0, 161)
INSERT INTO dbo.Pieces VALUES ('Lava Bubble Okorushi Stone', 0, 161)
INSERT INTO dbo.Pieces VALUES ('Lava Bubble Beastmaster Cap', 0, 161)
INSERT INTO dbo.Pieces VALUES ('Lava Bubble Dracnari Ceremonial Robe', 0, 161)
INSERT INTO dbo.Pieces VALUES ('Sable Bubble Sable Bubble Shell', 1, 162)
INSERT INTO dbo.Pieces VALUES ('Sable Bubble Pinch Of Taint', 0, 162)
INSERT INTO dbo.Pieces VALUES ('Sable Bubble Jackal Jaw', 0, 162)
INSERT INTO dbo.Pieces VALUES ('Sable Bubble Ram Horn', 0, 162)
INSERT INTO dbo.Pieces VALUES ('Sable Bubble Scorpion Stinger', 0, 162)
INSERT INTO dbo.Pieces VALUES ('Sable Bubble Gravedigger Dust', 0, 162)
INSERT INTO dbo.Pieces VALUES ('Sable Bubble Groundhog Paw', 0, 162)
INSERT INTO dbo.Pieces VALUES ('Sable Bubble Bobcat Tail', 0, 162)
INSERT INTO dbo.Pieces VALUES ('Sable Bubble Mutt''s Tongue', 0, 162)
INSERT INTO dbo.Pieces VALUES ('Sable Bubble Viscanti Hair', 0, 162)
INSERT INTO dbo.Pieces VALUES ('Sand Bubble Sand Bubble Shell', 1, 153)
INSERT INTO dbo.Pieces VALUES ('Sand Bubble Mound Of Sand', 0, 153)
INSERT INTO dbo.Pieces VALUES ('Sand Bubble Gila Lizard Tail', 0, 153)
INSERT INTO dbo.Pieces VALUES ('Sand Bubble Wakabi Feather', 0, 153)
INSERT INTO dbo.Pieces VALUES ('Sand Bubble Coyote Fur', 0, 153)
INSERT INTO dbo.Pieces VALUES ('Sand Bubble Sandojin Talon', 0, 153)
INSERT INTO dbo.Pieces VALUES ('Sand Bubble Roadrunner Beak', 0, 153)
INSERT INTO dbo.Pieces VALUES ('Sand Bubble Cobra Skin', 0, 153)
INSERT INTO dbo.Pieces VALUES ('Sand Bubble Dashro Tongue', 0, 153)
INSERT INTO dbo.Pieces VALUES ('Smoke Bubble Smoke Bubble Shell', 1, 163)
INSERT INTO dbo.Pieces VALUES ('Smoke Bubble Rattlesnake Skin', 0, 163)
INSERT INTO dbo.Pieces VALUES ('Smoke Bubble Grouse Beak', 0, 163)
INSERT INTO dbo.Pieces VALUES ('Smoke Bubble Goat Horn', 0, 163)
INSERT INTO dbo.Pieces VALUES ('Smoke Bubble Spawn Claw', 0, 163)
INSERT INTO dbo.Pieces VALUES ('Smoke Bubble Gopher Teeth', 0, 163)
INSERT INTO dbo.Pieces VALUES ('Smoke Bubble Essence Of Song', 0, 163)
INSERT INTO dbo.Pieces VALUES ('Smoke Bubble Hag''s Cauldron', 0, 163)
INSERT INTO dbo.Pieces VALUES ('Smoke Bubble Centaur''s Spear', 0, 163)
INSERT INTO dbo.Pieces VALUES ('Smoke Bubble Violet Flower', 0, 163)
GO

INSERT INTO dbo.Collections VALUES ('Exotic')
INSERT INTO dbo.Collections VALUES ('Burger')
GO

INSERT INTO dbo.Sets VALUES ('Dill Bottle', 56)
INSERT INTO dbo.Sets VALUES ('Coriander Bottle', 56)
INSERT INTO dbo.Sets VALUES ('Mayonnaise Bottle', 57)
INSERT INTO dbo.Sets VALUES ('Mustard Bottle', 57)
INSERT INTO dbo.Sets VALUES ('Sage Bottle', 53)
INSERT INTO dbo.Sets VALUES ('Ginger Bottle', 55)
INSERT INTO dbo.Sets VALUES ('Paprika Bottle', 51)
GO

INSERT INTO dbo.Pieces VALUES ('Dill Bottle Empty Dill Bottle', 1, 164)
INSERT INTO dbo.Pieces VALUES ('Dill Bottle First Pinch Of Dill', 0, 164)
INSERT INTO dbo.Pieces VALUES ('Dill Bottle Second Pinch Of Dill', 0, 164)
INSERT INTO dbo.Pieces VALUES ('Dill Bottle Third Pinch Of Dill', 0, 164)
INSERT INTO dbo.Pieces VALUES ('Dill Bottle Fourth Pinch Of Dill', 0, 164)
INSERT INTO dbo.Pieces VALUES ('Dill Bottle Fifth Pinch Of Dill', 0, 164)
INSERT INTO dbo.Pieces VALUES ('Dill Bottle Sixth Pinch Of Dill', 0, 164)
INSERT INTO dbo.Pieces VALUES ('Dill Bottle Seventh Pinch Of Dill', 0, 164)
INSERT INTO dbo.Pieces VALUES ('Dill Bottle Eighth Pinch Of Dill', 0, 164)
INSERT INTO dbo.Pieces VALUES ('Dill Bottle Ninth Pinch Of Dill', 0, 164)
INSERT INTO dbo.Pieces VALUES ('Coriander Bottle First Pinch Of Coriander', 0, 165)
INSERT INTO dbo.Pieces VALUES ('Coriander Bottle Second Pinch Of Coriander', 0, 165)
INSERT INTO dbo.Pieces VALUES ('Coriander Bottle Third Pinch Of Coriander', 0, 165)
INSERT INTO dbo.Pieces VALUES ('Coriander Bottle Fourth Pinch Of Coriander', 0, 165)
INSERT INTO dbo.Pieces VALUES ('Coriander Bottle Fifth Pinch Of Coriander', 0, 165)
INSERT INTO dbo.Pieces VALUES ('Coriander Bottle Sixth Pinch Of Coriander', 0, 165)
INSERT INTO dbo.Pieces VALUES ('Coriander Bottle Seventh Pinch Of Coriander', 0, 165)
INSERT INTO dbo.Pieces VALUES ('Coriander Bottle Eighth Pinch Of Coriander', 0, 165)
INSERT INTO dbo.Pieces VALUES ('Coriander Bottle Ninth Pinch Of Coriander', 0, 165)
INSERT INTO dbo.Pieces VALUES ('Mayonnaise Bottle First Squirt Of Mayonnaise', 0, 166)
INSERT INTO dbo.Pieces VALUES ('Mayonnaise Bottle Second Squirt Of Mayonnaise', 0, 166)
INSERT INTO dbo.Pieces VALUES ('Mayonnaise Bottle Third Squirt Of Mayonnaise', 0, 166)
INSERT INTO dbo.Pieces VALUES ('Mayonnaise Bottle Fourth Squirt Of Mayonnaise', 0, 166)
INSERT INTO dbo.Pieces VALUES ('Mayonnaise Bottle Fifth Squirt Of Mayonnaise', 0, 166)
INSERT INTO dbo.Pieces VALUES ('Mayonnaise Bottle Sixth Squirt Of Mayonnaise', 0, 166)
INSERT INTO dbo.Pieces VALUES ('Mayonnaise Bottle Seventh Squirt Of Mayonnaise', 0, 166)
INSERT INTO dbo.Pieces VALUES ('Mayonnaise Bottle Eighth Squirt Of Mayonnaise', 0, 166)
INSERT INTO dbo.Pieces VALUES ('Mayonnaise Bottle Ninth Squirt Of Mayonnaise', 0, 166)
INSERT INTO dbo.Pieces VALUES ('Mustard Bottle First Squirt Of Mustard', 0, 167)
INSERT INTO dbo.Pieces VALUES ('Mustard Bottle Second Squirt Of Mustard', 0, 167)
INSERT INTO dbo.Pieces VALUES ('Mustard Bottle Third Squirt Of Mustard', 0, 167)
INSERT INTO dbo.Pieces VALUES ('Mustard Bottle Fourth Squirt Of Mustard', 0, 167)
INSERT INTO dbo.Pieces VALUES ('Mustard Bottle Fifth Squirt Of Mustard', 0, 167)
INSERT INTO dbo.Pieces VALUES ('Mustard Bottle Sixth Squirt Of Mustard', 0, 167)
INSERT INTO dbo.Pieces VALUES ('Mustard Bottle Seventh Squirt Of Mustard', 0, 167)
INSERT INTO dbo.Pieces VALUES ('Mustard Bottle Eighth Squirt Of Mustard', 0, 167)
INSERT INTO dbo.Pieces VALUES ('Mustard Bottle Ninth Squirt Of Mustard', 0, 167)
INSERT INTO dbo.Pieces VALUES ('Sage Bottle First Pinch Of Sage', 0, 168)
INSERT INTO dbo.Pieces VALUES ('Sage Bottle Second Pinch Of Sage', 0, 168)
INSERT INTO dbo.Pieces VALUES ('Sage Bottle Third Pinch Of Sage', 0, 168)
INSERT INTO dbo.Pieces VALUES ('Sage Bottle Fourth Pinch Of Sage', 0, 168)
INSERT INTO dbo.Pieces VALUES ('Sage Bottle Fifth Pinch Of Sage', 0, 168)
INSERT INTO dbo.Pieces VALUES ('Sage Bottle Sixth Pinch Of Sage', 0, 168)
INSERT INTO dbo.Pieces VALUES ('Sage Bottle Seventh Pinch Of Sage', 0, 168)
INSERT INTO dbo.Pieces VALUES ('Sage Bottle Eighth Pinch Of Sage', 0, 168)
INSERT INTO dbo.Pieces VALUES ('Sage Bottle Ninth Pinch Of Sage', 0, 168)
INSERT INTO dbo.Pieces VALUES ('Ginger Bottle First Pinch Of Ginger', 0, 169)
INSERT INTO dbo.Pieces VALUES ('Ginger Bottle Second Pinch Of Ginger', 0, 169)
INSERT INTO dbo.Pieces VALUES ('Ginger Bottle Third Pinch Of Ginger', 0, 169)
INSERT INTO dbo.Pieces VALUES ('Ginger Bottle Fourth Pinch Of Ginger', 0, 169)
INSERT INTO dbo.Pieces VALUES ('Ginger Bottle Fifth Pinch Of Ginger', 0, 169)
INSERT INTO dbo.Pieces VALUES ('Ginger Bottle Sixth Pinch Of Ginger', 0, 169)
INSERT INTO dbo.Pieces VALUES ('Ginger Bottle Seventh Pinch Of Ginger', 0, 169)
INSERT INTO dbo.Pieces VALUES ('Ginger Bottle Eighth Pinch Of Ginger', 0, 169)
INSERT INTO dbo.Pieces VALUES ('Ginger Bottle Ninth Pinch Of Ginger', 0, 169)
INSERT INTO dbo.Pieces VALUES ('Paprika Bottle First Pinch Of Paprika', 0, 170)
INSERT INTO dbo.Pieces VALUES ('Paprika Bottle Second Pinch Of Paprika', 0, 170)
INSERT INTO dbo.Pieces VALUES ('Paprika Bottle Third Pinch Of Paprika', 0, 170)
INSERT INTO dbo.Pieces VALUES ('Paprika Bottle Fourth Pinch Of Paprika', 0, 170)
INSERT INTO dbo.Pieces VALUES ('Paprika Bottle Fifth Pinch Of Paprika', 0, 170)
INSERT INTO dbo.Pieces VALUES ('Paprika Bottle Sixth Pinch Of Paprika', 0, 170)
INSERT INTO dbo.Pieces VALUES ('Paprika Bottle Seventh Pinch Of Paprika', 0, 170)
INSERT INTO dbo.Pieces VALUES ('Paprika Bottle Eighth Pinch Of Paprika', 0, 170)
INSERT INTO dbo.Pieces VALUES ('Paprika Bottle Ninth Pinch Of Paprika', 0, 170)
GO

INSERT INTO dbo.Collections VALUES ('Curry')
GO

INSERT INTO dbo.Sets VALUES ('Garlic Bottle', 58)
GO

INSERT INTO dbo.Pieces VALUES ('Garlic Bottle Empty Garlic Bottle', 0, 171)
INSERT INTO dbo.Pieces VALUES ('Garlic Bottle First Pinch Of Garlic', 0, 171)
INSERT INTO dbo.Pieces VALUES ('Garlic Bottle Second Pinch Of Garlic', 0, 171)
INSERT INTO dbo.Pieces VALUES ('Garlic Bottle Third Pinch Of Garlic', 0, 171)
INSERT INTO dbo.Pieces VALUES ('Garlic Bottle Fourth Pinch Of Garlic', 0, 171)
INSERT INTO dbo.Pieces VALUES ('Garlic Bottle Fifth Pinch Of Garlic', 0, 171)
INSERT INTO dbo.Pieces VALUES ('Garlic Bottle Sixth Pinch Of Garlic', 0, 171)
INSERT INTO dbo.Pieces VALUES ('Garlic Bottle Seventh Pinch Of Garlic', 0, 171)
INSERT INTO dbo.Pieces VALUES ('Garlic Bottle Eighth Pinch Of Garlic', 0, 171)
INSERT INTO dbo.Pieces VALUES ('Garlic Bottle Ninth Pinch Of Garlic', 0, 171)
GO

INSERT INTO dbo.Pieces VALUES ('Swan Mask Swan Mask Head', 1, 146)
INSERT INTO dbo.Pieces VALUES ('Swan Mask Swan Right Eye', 0, 146)
INSERT INTO dbo.Pieces VALUES ('Swan Mask Swan Left Eye', 0, 146)
INSERT INTO dbo.Pieces VALUES ('Swan Mask Swan Right Cheek', 0, 146)
INSERT INTO dbo.Pieces VALUES ('Swan Mask Swan Left Cheek', 0, 146)
INSERT INTO dbo.Pieces VALUES ('Swan Mask Swan Upper Beak', 0, 146)
INSERT INTO dbo.Pieces VALUES ('Swan Mask Swan Lower Beak', 0, 146)
INSERT INTO dbo.Pieces VALUES ('Swan Mask Swan Forehead', 0, 146)
INSERT INTO dbo.Pieces VALUES ('Swan Mask Swan Mask Strap', 0, 146)
INSERT INTO dbo.Pieces VALUES ('Chicken Mask Chicken Right Cheek', 0, 147)
GO

INSERT INTO dbo.Pieces VALUES ('Maiden Mask Maiden Mask Head', 1, 148)
INSERT INTO dbo.Pieces VALUES ('Maiden Mask Maiden Right Eye', 0, 148)
INSERT INTO dbo.Pieces VALUES ('Maiden Mask Maiden Left Eye', 0, 148)
INSERT INTO dbo.Pieces VALUES ('Maiden Mask Maiden Right Cheek', 0, 148)
INSERT INTO dbo.Pieces VALUES ('Maiden Mask Maiden Upper Mouth', 0, 148)
INSERT INTO dbo.Pieces VALUES ('Maiden Mask Maiden Lower Mouth', 0, 148)
INSERT INTO dbo.Pieces VALUES ('Maiden Mask Maiden Nose', 0, 148)
INSERT INTO dbo.Pieces VALUES ('Maiden Mask Maiden Chin', 0, 148)
INSERT INTO dbo.Pieces VALUES ('Maiden Mask Maiden Left Cheeck', 0, 148)
GO