INSERT INTO dbo.Sets VALUES ('Red Heart', 47)
GO

INSERT INTO dbo.Pieces VALUES ('Red Heart Heart-shaped Box', 1, 120)
INSERT INTO dbo.Pieces VALUES ('Red Heart Scarlet Candy', 0, 120)
INSERT INTO dbo.Pieces VALUES ('Red Heart Bright Blue Candy', 0, 120)
INSERT INTO dbo.Pieces VALUES ('Red Heart Pastel Yellow Candy', 0, 120)
INSERT INTO dbo.Pieces VALUES ('Red Heart Gold Candy', 0, 120)
INSERT INTO dbo.Pieces VALUES ('Red Heart Pitch Black Candy', 0, 120)
INSERT INTO dbo.Pieces VALUES ('Red Heart Burnt Orange Candy', 0, 120)
INSERT INTO dbo.Pieces VALUES ('Red Heart Rainbow Candy', 0, 120)
INSERT INTO dbo.Pieces VALUES ('Red Heart Hot Pink Candy', 0, 120)
INSERT INTO dbo.Pieces VALUES ('Red Heart Seafoam Green Candy', 0, 120)
GO

INSERT INTO dbo.Collections VALUES ('Redgenies')
INSERT INTO dbo.Collections VALUES ('Bluegenies')
INSERT INTO dbo.Collections VALUES ('Yellowgenies')
GO

INSERT INTO dbo.Sets VALUES ('Vermillion Bottle', 48)
INSERT INTO dbo.Sets VALUES ('Crimson Bottle', 48)
INSERT INTO dbo.Sets VALUES ('Scarlet Bottle', 48)
INSERT INTO dbo.Sets VALUES ('Ruby Bottle', 48)
GO

INSERT INTO dbo.Pieces VALUES ('Vermillion Bottle Spout', 1, 121)
INSERT INTO dbo.Pieces VALUES ('Vermillion Bottle First Vermillion Bottle Shard', 0, 121)
INSERT INTO dbo.Pieces VALUES ('Vermillion Bottle Second Vermillion Bottle Shard', 0, 121)
INSERT INTO dbo.Pieces VALUES ('Vermillion Bottle Third Vermillion Bottle Shard', 0, 121)
INSERT INTO dbo.Pieces VALUES ('Vermillion Bottle Fourth Vermillion Bottle Shard', 0, 121)
INSERT INTO dbo.Pieces VALUES ('Vermillion Bottle Fifth Vermillion Bottle Shard', 0, 121)
INSERT INTO dbo.Pieces VALUES ('Vermillion Bottle Sixth Vermillion Bottle Shard', 0, 121)
INSERT INTO dbo.Pieces VALUES ('Vermillion Bottle Seventh Vermillion Bottle Shard', 0, 121)
INSERT INTO dbo.Pieces VALUES ('Vermillion Bottle Eighth Vermillion Bottle Shard', 0, 121)
INSERT INTO dbo.Pieces VALUES ('Vermillion Bottle Ninth Vermillion Bottle Shard', 0, 121)
INSERT INTO dbo.Pieces VALUES ('Crimson Bottle Spout', 1, 122)
INSERT INTO dbo.Pieces VALUES ('Crimson Bottle First Crimson Bottle Shard', 0, 122)
INSERT INTO dbo.Pieces VALUES ('Crimson Bottle Second Crimson Bottle Shard', 0, 122)
INSERT INTO dbo.Pieces VALUES ('Crimson Bottle Third Crimson Bottle Shard', 0, 122)
INSERT INTO dbo.Pieces VALUES ('Crimson Bottle Fourth Crimson Bottle Shard', 0, 122)
INSERT INTO dbo.Pieces VALUES ('Crimson Bottle Fifth Crimson Bottle Shard', 0, 122)
INSERT INTO dbo.Pieces VALUES ('Crimson Bottle Sixth Crimson Bottle Shard', 0, 122)
INSERT INTO dbo.Pieces VALUES ('Crimson Bottle Seventh Crimson Bottle Shard', 0, 122)
INSERT INTO dbo.Pieces VALUES ('Crimson Bottle Eighth Crimson Bottle Shard', 0, 122)
INSERT INTO dbo.Pieces VALUES ('Crimson Bottle Ninth Crimson Bottle Shard', 0, 122)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bottle Spout', 1, 123)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bottle First Scarlet Bottle Shard', 0, 123)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bottle Second Scarlet Bottle Shard', 0, 123)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bottle Third Scarlet Bottle Shard', 0, 123)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bottle Fourth Scarlet Bottle Shard', 0, 123)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bottle Fifth Scarlet Bottle Shard', 0, 123)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bottle Sixth Scarlet Bottle Shard', 0, 123)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bottle Seventh Scarlet Bottle Shard', 0, 123)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bottle Eighth Scarlet Bottle Shard', 0, 123)
INSERT INTO dbo.Pieces VALUES ('Scarlet Bottle Ninth Scarlet Bottle Shard', 0, 123)
INSERT INTO dbo.Pieces VALUES ('Ruby Bottle Spout', 1, 124)
INSERT INTO dbo.Pieces VALUES ('Ruby Bottle First Ruby Bottle Shard', 0, 124)
INSERT INTO dbo.Pieces VALUES ('Ruby Bottle Second Ruby Bottle Shard', 0, 124)
INSERT INTO dbo.Pieces VALUES ('Ruby Bottle Third Ruby Bottle Shard', 0, 124)
INSERT INTO dbo.Pieces VALUES ('Ruby Bottle Fourth Ruby Bottle Shard', 0, 124)
INSERT INTO dbo.Pieces VALUES ('Ruby Bottle Fifth Ruby Bottle Shard', 0, 124)
INSERT INTO dbo.Pieces VALUES ('Ruby Bottle Sixth Ruby Bottle Shard', 0, 124)
INSERT INTO dbo.Pieces VALUES ('Ruby Bottle Seventh Ruby Bottle Shard', 0, 124)
INSERT INTO dbo.Pieces VALUES ('Ruby Bottle Eighth Ruby Bottle Shard', 0, 124)
INSERT INTO dbo.Pieces VALUES ('Ruby Bottle Ninth Ruby Bottle Shard', 0, 124)
GO

INSERT INTO dbo.Sets VALUES ('Cerulean Bottle', 49)
INSERT INTO dbo.Sets VALUES ('Sapphire Bottle', 49)
INSERT INTO dbo.Sets VALUES ('Lavender Bottle', 49)
INSERT INTO dbo.Sets VALUES ('Azure Bottle', 49)
INSERT INTO dbo.Sets VALUES ('Gold Bottle', 50)
INSERT INTO dbo.Sets VALUES ('Saffron Bottle', 50)
INSERT INTO dbo.Sets VALUES ('Citrine Bottle', 50)
INSERT INTO dbo.Sets VALUES ('Amber Bottle', 50)
GO

INSERT INTO dbo.Pieces VALUES ('Cerulean Bottle Spout', 1, 125)
INSERT INTO dbo.Pieces VALUES ('Cerulean Bottle First Cerulean Bottle Shard', 0, 125)
INSERT INTO dbo.Pieces VALUES ('Cerulean Bottle Second Cerulean Bottle Shard', 0, 125)
INSERT INTO dbo.Pieces VALUES ('Cerulean Bottle Third Cerulean Bottle Shard', 0, 125)
INSERT INTO dbo.Pieces VALUES ('Cerulean Bottle Fourth Cerulean Bottle Shard', 0, 125)
INSERT INTO dbo.Pieces VALUES ('Cerulean Bottle Fifth Cerulean Bottle Shard', 0, 125)
INSERT INTO dbo.Pieces VALUES ('Cerulean Bottle Sixth Cerulean Bottle Shard', 0, 125)
INSERT INTO dbo.Pieces VALUES ('Cerulean Bottle Seventh Cerulean Bottle Shard', 0, 125)
INSERT INTO dbo.Pieces VALUES ('Cerulean Bottle Eighth Cerulean Bottle Shard', 0, 125)
INSERT INTO dbo.Pieces VALUES ('Cerulean Bottle Ninth Cerulean Bottle Shard', 0, 125)
INSERT INTO dbo.Pieces VALUES ('Sapphire Bottle Spout', 1, 126)
INSERT INTO dbo.Pieces VALUES ('Sapphire Bottle First Sapphire Bottle Shard', 0, 126)
INSERT INTO dbo.Pieces VALUES ('Sapphire Bottle Second Sapphire Bottle Shard', 0, 126)
INSERT INTO dbo.Pieces VALUES ('Sapphire Bottle Third Sapphire Bottle Shard', 0, 126)
INSERT INTO dbo.Pieces VALUES ('Sapphire Bottle Fourth Sapphire Bottle Shard', 0, 126)
INSERT INTO dbo.Pieces VALUES ('Sapphire Bottle Fifth Sapphire Bottle Shard', 0, 126)
INSERT INTO dbo.Pieces VALUES ('Sapphire Bottle Sixth Sapphire Bottle Shard', 0, 126)
INSERT INTO dbo.Pieces VALUES ('Sapphire Bottle Seventh Sapphire Bottle Shard', 0, 126)
INSERT INTO dbo.Pieces VALUES ('Sapphire Bottle Eighth Sapphire Bottle Shard', 0, 126)
INSERT INTO dbo.Pieces VALUES ('Sapphire Bottle Ninth Sapphire Bottle Shard', 0, 126)
INSERT INTO dbo.Pieces VALUES ('Lavender Bottle Spout', 1, 127)
INSERT INTO dbo.Pieces VALUES ('Lavender Bottle First Lavender Bottle Shard', 0, 127)
INSERT INTO dbo.Pieces VALUES ('Lavender Bottle Second Lavender Bottle Shard', 0, 127)
INSERT INTO dbo.Pieces VALUES ('Lavender Bottle Third Lavender Bottle Shard', 0, 127)
INSERT INTO dbo.Pieces VALUES ('Lavender Bottle Fourth Lavender Bottle Shard', 0, 127)
INSERT INTO dbo.Pieces VALUES ('Lavender Bottle Fifth Lavender Bottle Shard', 0, 127)
INSERT INTO dbo.Pieces VALUES ('Lavender Bottle Sixth Lavender Bottle Shard', 0, 127)
INSERT INTO dbo.Pieces VALUES ('Lavender Bottle Seventh Lavender Bottle Shard', 0, 127)
INSERT INTO dbo.Pieces VALUES ('Lavender Bottle Eighth Lavender Bottle Shard', 0, 127)
INSERT INTO dbo.Pieces VALUES ('Lavender Bottle Ninth Lavender Bottle Shard', 0, 127)
INSERT INTO dbo.Pieces VALUES ('Azure Bottle Spout', 1, 128)
INSERT INTO dbo.Pieces VALUES ('Azure Bottle First Azure Bottle Shard', 0, 128)
INSERT INTO dbo.Pieces VALUES ('Azure Bottle Second Azure Bottle Shard', 0, 128)
INSERT INTO dbo.Pieces VALUES ('Azure Bottle Third Azure Bottle Shard', 0, 128)
INSERT INTO dbo.Pieces VALUES ('Azure Bottle Fourth Azure Bottle Shard', 0, 128)
INSERT INTO dbo.Pieces VALUES ('Azure Bottle Fifth Azure Bottle Shard', 0, 128)
INSERT INTO dbo.Pieces VALUES ('Azure Bottle Sixth Azure Bottle Shard', 0, 128)
INSERT INTO dbo.Pieces VALUES ('Azure Bottle Seventh Azure Bottle Shard', 0, 128)
INSERT INTO dbo.Pieces VALUES ('Azure Bottle Eighth Azure Bottle Shard', 0, 128)
INSERT INTO dbo.Pieces VALUES ('Azure Bottle Ninth Azure Bottle Shard', 0, 128)
INSERT INTO dbo.Pieces VALUES ('Gold Bottle Spout', 1, 129)
INSERT INTO dbo.Pieces VALUES ('Gold Bottle First Gold Bottle Shard', 0, 129)
INSERT INTO dbo.Pieces VALUES ('Gold Bottle Second Gold Bottle Shard', 0, 129)
INSERT INTO dbo.Pieces VALUES ('Gold Bottle Third Gold Bottle Shard', 0, 129)
INSERT INTO dbo.Pieces VALUES ('Gold Bottle Fourth Gold Bottle Shard', 0, 129)
INSERT INTO dbo.Pieces VALUES ('Gold Bottle Fifth Gold Bottle Shard', 0, 129)
INSERT INTO dbo.Pieces VALUES ('Gold Bottle Sixth Gold Bottle Shard', 0, 129)
INSERT INTO dbo.Pieces VALUES ('Gold Bottle Seventh Gold Bottle Shard', 0, 129)
INSERT INTO dbo.Pieces VALUES ('Gold Bottle Eighth Gold Bottle Shard', 0, 129)
INSERT INTO dbo.Pieces VALUES ('Gold Bottle Ninth Gold Bottle Shard', 0, 129)
INSERT INTO dbo.Pieces VALUES ('Saffron Bottle Spout', 1, 130)
INSERT INTO dbo.Pieces VALUES ('Saffron Bottle First Saffron Bottle Shard', 0, 130)
INSERT INTO dbo.Pieces VALUES ('Saffron Bottle Second Saffron Bottle Shard', 0, 130)
INSERT INTO dbo.Pieces VALUES ('Saffron Bottle Third Saffron Bottle Shard', 0, 130)
INSERT INTO dbo.Pieces VALUES ('Saffron Bottle Fourth Saffron Bottle Shard', 0, 130)
INSERT INTO dbo.Pieces VALUES ('Saffron Bottle Fifth Saffron Bottle Shard', 0, 130)
INSERT INTO dbo.Pieces VALUES ('Saffron Bottle Sixth Saffron Bottle Shard', 0, 130)
INSERT INTO dbo.Pieces VALUES ('Saffron Bottle Seventh Saffron Bottle Shard', 0, 130)
INSERT INTO dbo.Pieces VALUES ('Saffron Bottle Eighth Saffron Bottle Shard', 0, 130)
INSERT INTO dbo.Pieces VALUES ('Saffron Bottle Ninth Saffron Bottle Shard', 0, 130)
INSERT INTO dbo.Pieces VALUES ('Citrine Bottle Spout', 1, 131)
INSERT INTO dbo.Pieces VALUES ('Citrine Bottle First Citrine Bottle Shard', 0, 131)
INSERT INTO dbo.Pieces VALUES ('Citrine Bottle Second Citrine Bottle Shard', 0, 131)
INSERT INTO dbo.Pieces VALUES ('Citrine Bottle Third Citrine Bottle Shard', 0, 131)
INSERT INTO dbo.Pieces VALUES ('Citrine Bottle Fourth Citrine Bottle Shard', 0, 131)
INSERT INTO dbo.Pieces VALUES ('Citrine Bottle Fifth Citrine Bottle Shard', 0, 131)
INSERT INTO dbo.Pieces VALUES ('Citrine Bottle Sixth Citrine Bottle Shard', 0, 131)
INSERT INTO dbo.Pieces VALUES ('Citrine Bottle Seventh Citrine Bottle Shard', 0, 131)
INSERT INTO dbo.Pieces VALUES ('Citrine Bottle Eighth Citrine Bottle Shard', 0, 131)
INSERT INTO dbo.Pieces VALUES ('Citrine Bottle Ninth Citrine Bottle Shard', 0, 131)
INSERT INTO dbo.Pieces VALUES ('Amber Bottle Spout', 1, 132)
INSERT INTO dbo.Pieces VALUES ('Amber Bottle First Amber Bottle Shard', 0, 132)
INSERT INTO dbo.Pieces VALUES ('Amber Bottle Second Amber Bottle Shard', 0, 132)
INSERT INTO dbo.Pieces VALUES ('Amber Bottle Third Amber Bottle Shard', 0, 132)
INSERT INTO dbo.Pieces VALUES ('Amber Bottle Fourth Amber Bottle Shard', 0, 132)
INSERT INTO dbo.Pieces VALUES ('Amber Bottle Fifth Amber Bottle Shard', 0, 132)
INSERT INTO dbo.Pieces VALUES ('Amber Bottle Sixth Amber Bottle Shard', 0, 132)
INSERT INTO dbo.Pieces VALUES ('Amber Bottle Seventh Amber Bottle Shard', 0, 132)
INSERT INTO dbo.Pieces VALUES ('Amber Bottle Eighth Amber Bottle Shard', 0, 132)
INSERT INTO dbo.Pieces VALUES ('Amber Bottle Ninth Amber Bottle Shard', 0, 132)
GO

INSERT INTO dbo.Collections VALUES ('Fried')
INSERT INTO dbo.Collections VALUES ('Chocolate')
GO

INSERT INTO dbo.Sets VALUES ('Allspice Bottle', 51)
INSERT INTO dbo.Sets VALUES ('Powdered Sugar Bottle', 52)
INSERT INTO dbo.Sets VALUES ('Love Bottle', 52)
INSERT INTO dbo.Sets VALUES ('White Bubble', 47)
INSERT INTO dbo.Sets VALUES ('Purple Bubble', 47)
INSERT INTO dbo.Sets VALUES ('Grey Bubble', 47)
INSERT INTO dbo.Sets VALUES ('Black bubble', 47)
GO

INSERT INTO dbo.Pieces VALUES ('Allspice Bottle Empty Allspice Bottle', 1, 133)
INSERT INTO dbo.Pieces VALUES ('Allspice Bottle First Pinch Of Allspice', 0, 133)
INSERT INTO dbo.Pieces VALUES ('Allspice Bottle Second Pinch Of Allspice', 0, 133)
INSERT INTO dbo.Pieces VALUES ('Allspice Bottle Third Pinch Of Allspice', 0, 133)
INSERT INTO dbo.Pieces VALUES ('Allspice Bottle Fourth Pinch Of Allspice', 0, 133)
INSERT INTO dbo.Pieces VALUES ('Allspice Bottle Fifth Pinch Of Allspice', 0, 133)
INSERT INTO dbo.Pieces VALUES ('Allspice Bottle Sixth Pinch Of Allspice', 0, 133)
INSERT INTO dbo.Pieces VALUES ('Allspice Bottle Seventh Pinch Of Allspice', 0, 133)
INSERT INTO dbo.Pieces VALUES ('Allspice Bottle Eighth Pinch Of Allspice', 0, 133)
INSERT INTO dbo.Pieces VALUES ('Allspice Bottle Ninth Pinch Of Allspice', 0, 133)
INSERT INTO dbo.Pieces VALUES ('Powdered Sugar Bottle Spout', 1, 134)
INSERT INTO dbo.Pieces VALUES ('Powdered Sugar Bottle First Pinch Of Powdered Sugar', 0, 134)
INSERT INTO dbo.Pieces VALUES ('Powdered Sugar Bottle Second Pinch Of Powdered Sugar', 0, 134)
INSERT INTO dbo.Pieces VALUES ('Powdered Sugar Bottle Third Pinch Of Powdered Sugar', 0, 134)
INSERT INTO dbo.Pieces VALUES ('Powdered Sugar Bottle Fourth Pinch Of Powdered Sugar', 0, 134)
INSERT INTO dbo.Pieces VALUES ('Powdered Sugar Bottle Fifth Pinch Of Powdered Sugar', 0, 134)
INSERT INTO dbo.Pieces VALUES ('Powdered Sugar Bottle Sixth Pinch Of Powdered Sugar', 0, 134)
INSERT INTO dbo.Pieces VALUES ('Powdered Sugar Bottle Seventh Pinch Of Powdered Sugar', 0, 134)
INSERT INTO dbo.Pieces VALUES ('Powdered Sugar Bottle Eighth Pinch Of Powdered Sugar', 0, 134)
INSERT INTO dbo.Pieces VALUES ('Powdered Sugar Bottle Ninth Pinch Of Powdered Sugar', 0, 134)
INSERT INTO dbo.Pieces VALUES ('Love Bottle Spout', 1, 135)
INSERT INTO dbo.Pieces VALUES ('Love Bottle First Dollop Of Love', 0, 135)
INSERT INTO dbo.Pieces VALUES ('Love Bottle Second Dollop Of Love', 0, 135)
INSERT INTO dbo.Pieces VALUES ('Love Bottle Third Dollop Of Love', 0, 135)
INSERT INTO dbo.Pieces VALUES ('Love Bottle Fourth Dollop Of Love', 0, 135)
INSERT INTO dbo.Pieces VALUES ('Love Bottle Fifth Dollop Of Love', 0, 135)
INSERT INTO dbo.Pieces VALUES ('Love Bottle Sixth Dollop Of Love', 0, 135)
INSERT INTO dbo.Pieces VALUES ('Love Bottle Seventh Dollop Of Love', 0, 135)
INSERT INTO dbo.Pieces VALUES ('Love Bottle Eighth Dollop Of Love', 0, 135)
INSERT INTO dbo.Pieces VALUES ('Love Bottle Ninth Dollop Of Love', 0, 135)
INSERT INTO dbo.Pieces VALUES ('White Bubble White Bubble Shell', 1, 136)
INSERT INTO dbo.Pieces VALUES ('White Bubble Essence Of Chaos', 0, 136)
INSERT INTO dbo.Pieces VALUES ('White Bubble Essence Of Death', 0, 136)
INSERT INTO dbo.Pieces VALUES ('White Bubble Essence Of Knowledge', 0, 136)
INSERT INTO dbo.Pieces VALUES ('White Bubble Essence Of Beauty', 0, 136)
INSERT INTO dbo.Pieces VALUES ('White Bubble Essence Of Life', 0, 136)
INSERT INTO dbo.Pieces VALUES ('White Bubble Essence Of Justice', 0, 136)
INSERT INTO dbo.Pieces VALUES ('White Bubble Essence Of Nature', 0, 136)
INSERT INTO dbo.Pieces VALUES ('White Bubble Essence Of Harmony', 0, 136)
INSERT INTO dbo.Pieces VALUES ('White Bubble Essence Of War', 0, 136)
INSERT INTO dbo.Pieces VALUES ('Purple Bubble Purple Bubble Shell', 1, 137)
INSERT INTO dbo.Pieces VALUES ('Purple Bubble Butterfly Wings', 0, 137)
INSERT INTO dbo.Pieces VALUES ('Purple Bubble Perfume Bottle', 0, 137)
INSERT INTO dbo.Pieces VALUES ('Purple Bubble Mrriak Fur', 0, 137)
INSERT INTO dbo.Pieces VALUES ('Purple Bubble Aerial Feather', 0, 137)
INSERT INTO dbo.Pieces VALUES ('Purple Bubble Essence Of Snootiness', 0, 137)
INSERT INTO dbo.Pieces VALUES ('Purple Bubble Gardener''s Hat', 0, 137)
INSERT INTO dbo.Pieces VALUES ('Purple Bubble Flower Petals', 0, 137)
INSERT INTO dbo.Pieces VALUES ('Purple Bubble Maid''s Feather Duster', 0, 137)
INSERT INTO dbo.Pieces VALUES ('Purple Bubble Trill Feather', 0, 137)
INSERT INTO dbo.Pieces VALUES ('Grey Bubble Grey Bubble Shell', 1, 138)
INSERT INTO dbo.Pieces VALUES ('Grey Bubble Wolf Hair', 0, 138)
INSERT INTO dbo.Pieces VALUES ('Grey Bubble Hunter''s Knife', 0, 138)
INSERT INTO dbo.Pieces VALUES ('Grey Bubble Lupine Ectoplasm', 0, 138)
INSERT INTO dbo.Pieces VALUES ('Grey Bubble Green Grass', 0, 138)
INSERT INTO dbo.Pieces VALUES ('Grey Bubble Tidepool Water', 0, 138)
INSERT INTO dbo.Pieces VALUES ('Grey Bubble Standing Stone Chip', 0, 138)
INSERT INTO dbo.Pieces VALUES ('Grey Bubble Splinter Of A Wood Hut', 0, 138)
INSERT INTO dbo.Pieces VALUES ('Grey Bubble Fire Pit Ember', 0, 138)
INSERT INTO dbo.Pieces VALUES ('Grey Bubble Creek Stone', 0, 138)
INSERT INTO dbo.Pieces VALUES ('Black Bubble Black Bubble Shell', 1, 139)
INSERT INTO dbo.Pieces VALUES ('Black Bubble Fox Tail', 0, 139)
INSERT INTO dbo.Pieces VALUES ('Black Bubble Badger Tooth', 0, 139)
INSERT INTO dbo.Pieces VALUES ('Black Bubble Buck Horn', 0, 139)
INSERT INTO dbo.Pieces VALUES ('Black Bubble Cup Of Slime', 0, 139)
INSERT INTO dbo.Pieces VALUES ('Black Bubble Zombie Hand', 0, 139)
INSERT INTO dbo.Pieces VALUES ('Black Bubble Tendril Skin', 0, 139)
INSERT INTO dbo.Pieces VALUES ('Black Bubble Jar Of Tar', 0, 139)
INSERT INTO dbo.Pieces VALUES ('Black Bubble Petrified Tree Bark', 0, 139)
INSERT INTO dbo.Pieces VALUES ('Black Bubble Puddle Of Muck', 0, 139)
GO

INSERT INTO dbo.Sets VALUES ('Poteen Pot', 47)
GO

INSERT INTO dbo.Pieces VALUES ('Poteen Pot Poteen Pot', 1, 140)
INSERT INTO dbo.Pieces VALUES ('Poteen Pot Barrel Of Barley', 0, 140)
INSERT INTO dbo.Pieces VALUES ('Poteen Pot Handful Of Oats', 0, 140)
INSERT INTO dbo.Pieces VALUES ('Poteen Pot Fistful Of Rye', 0, 140)
INSERT INTO dbo.Pieces VALUES ('Poteen Pot Yummy Taters', 0, 140)
INSERT INTO dbo.Pieces VALUES ('Poteen Pot Malty Malt', 0, 140)
INSERT INTO dbo.Pieces VALUES ('Poteen Pot Treacle', 0, 140)
INSERT INTO dbo.Pieces VALUES ('Poteen Pot Sour Mash', 0, 140)
INSERT INTO dbo.Pieces VALUES ('Poteen Pot Washed Sand', 0, 140)
INSERT INTO dbo.Pieces VALUES ('Poteen Pot Bit O Magic', 0, 140)
GO

INSERT INTO dbo.Pieces VALUES ('straight razor straight razor rust', 0, 73)
GO