using CurioExchangeService.Entities;
using CurioExchangeService;
using System;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;

namespace CurioExchangeService.Migrations
{
    internal sealed class Configuration : DbMigrationsConfiguration<CurioExchangeContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
            ContextKey = "CurioExchangeService";
        }

        protected override void Seed(CurioExchangeContext context)
        {
            if (!context.Collections.Any() && !context.Sets.Any() && !context.Pieces.Any()) { 

            var none = new Collection { Name = "(None)" };
            var astro = new Collection { Name = "Astro" };
            var bird = new Collection { Name = "Bird" };
            var bone = new Collection { Name = "Bone" };
            var face = new Collection { Name = "Face" };
            var feather = new Collection { Name = "Feather" };
            var figure = new Collection { Name = "Figure" };
            var flower = new Collection { Name = "Flower" };
            var flutter = new Collection { Name = "Flutter" };
            var forsaken = new Collection { Name = "Forsaken" };
            var iceAngel = new Collection { Name = "Ice Angel" };
            var light = new Collection { Name = "Light" };
            var mechanical = new Collection { Name = "Mechanical" };
            var scholar = new Collection { Name = "Scholar" };
            var sky = new Collection { Name = "Sky" };
            var snake = new Collection { Name = "Snake" };
            var soulless = new Collection { Name = "Soulless" };
            var spider = new Collection { Name = "Spider" };
            var tool = new Collection { Name = "Tool" };
            var torture = new Collection { Name = "Torture" };
            var toy = new Collection { Name = "Toy" };
            var utensil = new Collection { Name = "Utensil" };
            var vernal = new Collection { Name = "Vernal" };
            var waystation = new Collection { Name = "Waystation" };

            context.Collections.Add(none);
            context.Collections.Add(astro);
            context.Collections.Add(bird);
            context.Collections.Add(bone);
            context.Collections.Add(face);
            context.Collections.Add(feather);
            context.Collections.Add(figure);
            context.Collections.Add(flower);
            context.Collections.Add(flutter);
            context.Collections.Add(forsaken);
            context.Collections.Add(iceAngel);
            context.Collections.Add(mechanical);
            context.Collections.Add(scholar);
            context.Collections.Add(sky);
            context.Collections.Add(snake);
            context.Collections.Add(soulless);
            context.Collections.Add(spider);
            context.Collections.Add(tool);
            context.Collections.Add(torture);
            context.Collections.Add(toy);
            context.Collections.Add(utensil);
            context.Collections.Add(vernal);
            context.Collections.Add(waystation);

            // todo: animated, fixture
            // var  = new Set { Name = "", Collection = };
            var splinteredStar = new Set { Name = "Splintered Star", Collection = astro };
            var crystalMoon = new Set { Name = "Crystal Moon", Collection = astro };
            var crystalComet = new Set { Name = "Crystal Comet", Collection = astro };
            var glitteringSun = new Set { Name = "Glittering Sun", Collection = astro };
            var glassPeacock = new Set { Name = "Glass Peacock", Collection = bird };
            var porcelainDove = new Set { Name = "Porcelain Dove", Collection = bird };
            var ceramicParrot = new Set { Name = "Ceramic Parrot", Collection = bird };
            var gemSwan = new Set { Name = "Gem Swan", Collection = bird };
            var diamondSkull = new Set { Name = "Diamond Skull", Collection = bone };
            var crystalFemur  = new Set { Name = "Crystal Femur", Collection = bone };
            var rubyRib  = new Set { Name = "Ruby Rib", Collection = bone };
            var knucklebone = new Set { Name = "Knucklebone", Collection = bone };
            var glaringEyeball = new Set { Name = "Glaring Eyeball", Collection = face };
            var sniffingNose = new Set { Name = "Sniffing Nose", Collection = face };
            var disembodiedMouth = new Set { Name = "Disembodied Mouth", Collection = face };
            var floatingEar  = new Set { Name = "Floating Ear", Collection = face };
            var goldenFeather = new Set { Name = "Golden Feather", Collection = feather };
            var silverFeather  = new Set { Name = "Silver Feather", Collection = feather };
            var bronzeFeather  = new Set { Name = "Bronze Feather", Collection = feather };
            var platinumFeather = new Set { Name = "Platinum Feather", Collection = feather };
            var woodenSoldier = new Set { Name = "Wooden Soldier", Collection = figure };
            var tinTinker = new Set { Name = "Tin Tinker", Collection = figure };
            var bronzeTailor  = new Set { Name = "Bronze Tailor", Collection = figure };
            var ironSpy = new Set { Name = "Iron Spy", Collection = figure };
            var gemRose  = new Set { Name = "Gem Rose", Collection = flower };
            var jewelOrchid = new Set { Name = "Jewel Orchid", Collection = flower };
            var rubyTulip  = new Set { Name = "Ruby Tulip", Collection = flower };
            var jeweledLily = new Set { Name = "Jeweled Lily", Collection = flower };
            var glassButterfly = new Set { Name = "Glass Butterfly", Collection = flutter };
            var jadeMoth = new Set { Name = "Jade Moth", Collection = flutter };
            var jeweledDragonfly = new Set { Name = "Jeweled Dragonfly", Collection = flutter };
            var goldenBumblebee = new Set { Name = "Golden Bumblebee", Collection = flutter };
            var jewelledSkull = new Set { Name = "Jewelled Skull", Collection = forsaken };
            var forsakenVelil  = new Set { Name = "Forsaken Veil", Collection = forsaken };
            var jewelledEye  = new Set { Name = "Jewelled Eye", Collection = forsaken };
            var frozenSpearhead = new Set { Name = "Frozen Spearhead", Collection = forsaken };
            var guardianMedal  = new Set { Name = "Guardian Medal", Collection = iceAngel };
            var cloudberryBasket  = new Set { Name = "Cloudberry Basket", Collection = iceAngel };
            var iceSkull  = new Set { Name = "Ice Skull", Collection = iceAngel };
            var phoenixPlume = new Set { Name = "Phoenix Plume", Collection = iceAngel };
            var bewitchLantern  = new Set { Name = "Bewitch Lantern", Collection = light };
            var runedTorch  = new Set { Name = "Runed Torch", Collection = light };
            var silverCandelabra  = new Set { Name = "Silver Candelabra", Collection = light };
            var murexBeacon = new Set { Name = "Murex Beacon ", Collection = light };
            var toothedCog  = new Set { Name = "Toothed Cog", Collection = mechanical };
            var oiledGear  = new Set { Name = "Oiled Gear", Collection = mechanical };
            var clockworkPendulum  = new Set { Name = "Clockwork Pendulum", Collection = mechanical };
            var brassSprocket = new Set { Name = "Brass Sprocket", Collection = mechanical };
            var featherQuill = new Set { Name = "Feather Quill", Collection = scholar };
            var squareInkwell = new Set { Name = "Square Inkwell", Collection = scholar };
            var scholarNotepad  = new Set { Name = "Scholar's Notepad", Collection = scholar };
            var silverPenknife = new Set { Name = "Silver Penknife", Collection = scholar };
            var whiteCloud  = new Set { Name = "White Cloud", Collection = sky };
            var shimmeringRainbow  = new Set { Name = "Shimmering Rainbow", Collection = sky };
            var icySnowflake  = new Set { Name = "Icy Snowflake", Collection = sky };
            var crystalLightning  = new Set { Name = "Crystal Lightning", Collection = sky };
            var avariciousAsp  = new Set { Name = "Avaricious Asp", Collection = snake };
            var emeraldCobra = new Set { Name = "Emerald Cobra", Collection = snake };
            var rapaciousRattlesnake  = new Set { Name = "Rapacious Rattlesnake", Collection = snake };
            var boaConstrictor = new Set { Name = "Boa Constrictor", Collection = snake };
            var corruptStaff = new Set { Name = "Corrupt Staff", Collection = soulless };
            var darkFlame = new Set { Name = "Dark Flame", Collection = soulless };
            var toxicSpine = new Set { Name = "Toxic Spine", Collection = soulless };
            var darkDiamond = new Set { Name = "Dark Diamond", Collection = soulless };
            var spiderweb = new Set { Name = "Spiderweb", Collection = spider };
            var leeringTarantula = new Set { Name = "Leering Tarantula", Collection = spider };
            var blackWidow = new Set { Name = "Black Widow", Collection = spider };
            var silkSpider= new Set { Name = "Silk Spider", Collection = spider };
            var steelWrench = new Set { Name = "Steel Wrench", Collection = tool };
            var screwdriver = new Set { Name = "Screwdriver", Collection = tool };
            var gleamingSaw = new Set { Name = "Gleaming Saw", Collection = tool };
            var oilyRatchet = new Set { Name = "Oily Ratchet", Collection = tool };
            var straightRazor  = new Set { Name = "Straight Razor", Collection = torture };
            var leatherFlog = new Set { Name = "Leather Flog", Collection = torture };
            var steelHandcuffs = new Set { Name = "Steel Handcuffs", Collection = torture };
            var sableBlindfold = new Set { Name = "Sable Blindfold", Collection = torture };
            var magicBear = new Set { Name = "Magic Bear", Collection = toy };
            var stuffedWakabi = new Set { Name = "Stuffed Wakabi", Collection = toy };
            var stuffedPiglet = new Set { Name = "Stuffed Piglet", Collection = toy };
            var stuffedDonkey = new Set { Name = "Stuffed Donkey", Collection = toy };
            var silverSpoon = new Set { Name = "Silver Spoon", Collection = utensil };
            var daintyFork  = new Set { Name = "Dainty Fork", Collection = utensil };
            var woodenTongs = new Set { Name = "Wooden Tongs", Collection = utensil };
            var butterknife = new Set { Name = "Butterknife", Collection = utensil };
            var chromaRod = new Set { Name = "Chroma Rod", Collection = vernal };
            var holyHelm = new Set { Name = "Holy Helm", Collection = vernal };
            var vernalBracers = new Set { Name = "Vernal Bracers", Collection = vernal };
            var pearlSandals = new Set { Name = "Pearl Sandals", Collection = vernal };
            var woodenLuggage = new Set { Name = "Wooden Luggage", Collection = waystation };
            var woodenDriver = new Set { Name = "Wooden Driver", Collection = waystation };
            var woodenWakabi = new Set { Name = "Wooden Wakabi", Collection = waystation };
            var woodenCarriage = new Set { Name = "Wooden Carriage", Collection = waystation };

            // context.Sets.Add();
            context.Sets.Add(splinteredStar);
            context.Sets.Add(crystalMoon);
            context.Sets.Add(crystalComet);
            context.Sets.Add(glitteringSun);
            context.Sets.Add(glassPeacock);
            context.Sets.Add(porcelainDove);
            context.Sets.Add(ceramicParrot);
            context.Sets.Add(ceramicParrot);
            context.Sets.Add(diamondSkull);
            context.Sets.Add(crystalFemur);
            context.Sets.Add(rubyRib);
            context.Sets.Add(knucklebone);
            context.Sets.Add(glaringEyeball);
            context.Sets.Add(sniffingNose);
            context.Sets.Add(disembodiedMouth);
            context.Sets.Add(floatingEar);
            context.Sets.Add(goldenFeather);
            context.Sets.Add(silverFeather);
            context.Sets.Add(bronzeFeather);
            context.Sets.Add(platinumFeather);
            context.Sets.Add(woodenSoldier);
            context.Sets.Add(tinTinker);
            context.Sets.Add(bronzeTailor);
            context.Sets.Add(ironSpy);
            context.Sets.Add(gemRose);
            context.Sets.Add(jewelOrchid);
            context.Sets.Add(rubyTulip);
            context.Sets.Add(jeweledLily);
            context.Sets.Add(glassButterfly);
            context.Sets.Add(jadeMoth);
            context.Sets.Add(jeweledDragonfly);
            context.Sets.Add(goldenBumblebee);
            context.Sets.Add(jewelledSkull);
            context.Sets.Add(forsakenVelil);
            context.Sets.Add(jewelledEye);
            context.Sets.Add(frozenSpearhead);
            context.Sets.Add(guardianMedal);
            context.Sets.Add(cloudberryBasket);
            context.Sets.Add(iceSkull);
            context.Sets.Add(phoenixPlume);
            context.Sets.Add(bewitchLantern);
            context.Sets.Add(runedTorch);
            context.Sets.Add(silverCandelabra);
            context.Sets.Add(murexBeacon);
            context.Sets.Add(toothedCog);
            context.Sets.Add(oiledGear);
            context.Sets.Add(clockworkPendulum);
            context.Sets.Add(brassSprocket);
            context.Sets.Add(featherQuill);
            context.Sets.Add(squareInkwell);
            context.Sets.Add(scholarNotepad);
            context.Sets.Add(silverPenknife);
            context.Sets.Add(whiteCloud);
            context.Sets.Add(shimmeringRainbow);
            context.Sets.Add(icySnowflake);
            context.Sets.Add(crystalLightning);
            context.Sets.Add(avariciousAsp);
            context.Sets.Add(emeraldCobra);
            context.Sets.Add(rapaciousRattlesnake);
            context.Sets.Add(boaConstrictor);
            context.Sets.Add(corruptStaff);
            context.Sets.Add(darkFlame);
            context.Sets.Add(toxicSpine);
            context.Sets.Add(darkDiamond);
            context.Sets.Add(spiderweb);
            context.Sets.Add(leeringTarantula);
            context.Sets.Add(blackWidow);
            context.Sets.Add(silkSpider);
            context.Sets.Add(steelWrench);
            context.Sets.Add(screwdriver);
            context.Sets.Add(gleamingSaw);
            context.Sets.Add(oilyRatchet);
            context.Sets.Add(straightRazor);
            context.Sets.Add(leatherFlog);
            context.Sets.Add(steelHandcuffs);
            context.Sets.Add(sableBlindfold);
            context.Sets.Add(magicBear);
            context.Sets.Add(stuffedWakabi);
            context.Sets.Add(stuffedPiglet);
            context.Sets.Add(stuffedDonkey);
            context.Sets.Add(silverSpoon);
            context.Sets.Add(daintyFork);
            context.Sets.Add(woodenTongs);
            context.Sets.Add(butterknife);
            context.Sets.Add(chromaRod);
            context.Sets.Add(holyHelm);
            context.Sets.Add(vernalBracers);
            context.Sets.Add(pearlSandals);
            context.Sets.Add(woodenLuggage);
            context.Sets.Add(woodenDriver);
            context.Sets.Add(woodenWakabi);
            context.Sets.Add(woodenCarriage);

            context.Pieces.Add(new Piece { Name = "First Gem Petal", Rare = false, Set = jewelOrchid });
            context.Pieces.Add(new Piece { Name = "Fluted Stem", Rare = true, Set = jewelOrchid });

            context.SaveChanges();

            }
        }
    }
}
